---
- name: prepare hosts
  hosts: all
  remote_user: ubuntu
  vars:
    zuul_user: zuul
    zuul_host: zuul.beta.fricklercloud.de
    webhook_token: webhooksecretvalue  # set me from command line
    db_user_pass: userpassword         # set me from command line
    db_root_pass: rootpassword         # set me from command line
  pre_tasks:
    - name: update all packages
      ansible.builtin.apt:
        update_cache: true
        name: '*'
        state: latest
      become: true

    - name: install required packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - docker.io
          - docker-compose
          - python3-docker
      become: true
    
    - name: add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_ssh_user }}"
        groups: docker
        append: true
      become: true

    - name: add group
      group:
        name: "{{ zuul_user }}"
      become: true

    - name: add user
      user:
        name: "{{ zuul_user }}"
        uid: 10001
        shell: /bin/bash
        group: "{{ zuul_user }}"
        groups: sudo
        append: true
        home: "/home/{{ zuul_user }}"
      become: true

  roles:
    - name: zuul-setup role
      role: zuul-ci
      vars:
        operator_user: "{{ zuul_user }}"
        zookeeper_fqdn: zookeeper_1.osism.tech
        connections:
          osfricklerzuulapp:
            driver: github
            webhook_token: "{{ webhook_token }}"
            app_id: 175556
            app_key: "/etc/zuul/pem-files/osfricklerzuulapp.pem"
          opendevorg:
            name: opendev
            driver: git
            baseurl: https://opendev.org
        tenants:
          - tenant:
              name: osism
              source:
                opendevorg:
                  untrusted-projects:
                    - zuul/zuul-jobs:
                        include:
                          - job
                osfricklerzuulapp:
                  config-projects:
                    - osfrickler/zuul_config:
                        load-branch: main
                  untrusted-projects:
                    - osfrickler/testbed
        database:
          user_name: zuul
          user_pass: "{{ db_user_pass }}"
          root_pass: "{{ db_root_pass }}"
          db_name: zuul
          # container_name:
          # mariadb: "zuul_mariadb"
          # zookeeper: "zuul_zookeeper"
          # nodepool_launcher: "zuul_nodepool_launcher"
          # zuul_scheduler: "zuul_scheduler"
          # zuul_web: "zuul_web"
          # zuul_executor: "zuul_executor"
          # log_server: "zuul_log_server"
        nodepool_labels:
          labels:
            - name: ubuntu-focal
          diskimages:
            - name: base
              abstract: True
              elements:
                - vm
                - simple-init
                - growroot
              env-vars:
                TMPDIR: /srv/dib_tmp
                DIB_CHECKSUM: '1'
                DIB_IMAGE_CACHE: /srv/dib_cache
          
            - name: ubuntu-focal
              parent: base
              pause: False
              rebuild-age: 86400
              elements:
                - ubuntu-minimal
              release: focal
              username: zuul
              env-vars:
                DIB_APT_LOCAL_CACHE: '0'
                DIB_DISABLE_APT_CLEANUP: '0'
                FS_TYPE: ext3

        nodepool_providers:
          providers:  # we need this sub-key. limitation of to_nice_yaml library
            - name: betacloud
              driver: openstack
              cloud: osism-ci
              boot-timeout: 600
              diskimages:
                - name: ubuntu-focal
              cloud-images: 
                - name: "Ubuntu 20.04"
                  username: ubuntu
              pools:
                - name: main
                  networks:
                    - net-to-external-harbott
                  security-groups:
                    - icmp-ssh
                  max-servers: 3
                  labels:
                    - name: ubuntu-focal
                      min-ram: 4000
                      cloud-image: "Ubuntu 20.04"
                      key-name: harbott
                      console-log: true
      become: true
