---
- name: prepare hosts
  hosts: all
  remote_user: ubuntu
  vars:
    zuul_user: zuul
    zuul_host: zuul01.osism.xyz
    zuul_logserver_fqdn: logs.osism.xyz
    zuul_webserver_fqdn: zuul.osism.xyz
    zuul_webserver_admin: info@osism.tech
    github_app_id: 180718
    github_pem_name: osism-zuul-app
    webhook_token: webhooksecretvalue  # set me from command line
    db_user_pass: userpassword         # set me from command line
    db_root_pass: rootpassword         # set me from command line
  pre_tasks:
    - name: update all packages
      ansible.builtin.apt:
        update_cache: true
        name: '*'
        state: latest
      become: true

    - name: install required packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - docker.io
          - docker-compose
          - python3-docker
          - python3-openstackclient
      become: true
    
    - name: add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_ssh_user }}"
        groups: docker
        append: true
      become: true

    - name: add group
      ansible.builtin.group:
        name: "{{ zuul_user }}"
      become: true

    - name: add user
      ansible.builtin.user:
        name: "{{ zuul_user }}"
        uid: 10001
        shell: /bin/bash
        group: "{{ zuul_user }}"
        groups: sudo
        append: true
        home: "/home/{{ zuul_user }}"
      become: true

    - name: Create /etc/openstack/
      ansible.builtin.file:
        state: directory
        path: /etc/openstack
        owner: root
        group: root
        mode: 0755
      become: true

    - name: Deploy clouds.yaml file
      ansible.builtin.copy:
        src: clouds.yaml
        dest: /etc/openstack/clouds.yaml
        owner: root
        group: zuul
        mode: '0640'
      become: true
    
    - name: Create keypair in the cloud
      openstack.cloud.keypair:
        cloud: osism-ci
        name: osism-zuul
        public_key: "{{ lookup('file', 'nodepool.pub') }}"
      become: true

  roles:
    - name: zuul-setup role
      role: zuul
      vars:
        operator_user: "{{ zuul_user }}"
        zookeeper_fqdn: zookeeper01.osism.xyz
        connections:
          github:
            driver: github
            webhook_token: "{{ webhook_token }}"
            app_id: "{{ github_app_id }}"
            app_key: "/etc/zuul/pem-files/{{ github_pem_name }}.pem"
          opendevorg:
            name: opendev
            driver: git
            baseurl: https://opendev.org
        tenants:
          - tenant:
              name: osism
              source:
                opendevorg:
                  untrusted-projects:
                    - zuul/zuul-jobs:
                        include:
                          - job
                github:
                  config-projects:
                    - osism/zuul_config:
                        load-branch: main
                  untrusted-projects:
                    - osfrickler/cirros
                    - osfrickler/testbed
                    - osism/ansible-collection-commons
                    - osism/ansible-collection-services
                    - osism/ansible-collection-validations
                    - osism/ansible-defaults
                    - osism/ansible-lint-action
                    - osism/ansible-playbooks
                    - osism/container-image-ceph-ansible
                    - osism/container-image-inventory-reconciler
                    - osism/container-image-kolla-ansible
                    - osism/container-image-osism-ansible
                    - osism/container-image-uyuni
                    - osism/container-images
                    - osism/container-images-kolla
                    - osism/documentation
                    - osism/mappings
                    - osism/python-osism
                    - osism/release
                    - osism/testbed
                    - osism/zuul_jobs
        database:
          user_name: zuul
          user_pass: "{{ db_user_pass }}"
          root_pass: "{{ db_root_pass }}"
          db_name: zuul
        nodepool_labels:
          labels:
            - name: ubuntu-focal
          diskimages:
            - name: base
              abstract: True
              elements:
                - vm
                - simple-init
                - growroot
              env-vars:
                TMPDIR: /srv/dib_tmp
                DIB_CHECKSUM: '1'
                DIB_IMAGE_CACHE: /srv/dib_cache
          
            - name: ubuntu-focal
              parent: base
              pause: False
              rebuild-age: 86400
              elements:
                - ubuntu-minimal
              release: focal
              username: zuul
              env-vars:
                DIB_APT_LOCAL_CACHE: '0'
                DIB_DISABLE_APT_CLEANUP: '0'
                FS_TYPE: ext3

        nodepool_providers:
          providers:  # we need this sub-key. limitation of to_nice_yaml library
            - name: betacloud
              driver: openstack
              cloud: osism-ci
              boot-timeout: 600
              diskimages:
                - name: ubuntu-focal
              cloud-images: 
                - name: "Ubuntu 20.04"
                  username: ubuntu
              pools:
                - name: main
                  networks:
                    - net-to-external-osism-ci
                  security-groups:
                    - zuul-worker-node
                  max-servers: 3
                  labels:
                    - name: ubuntu-focal
                      min-ram: 4000
                      cloud-image: "Ubuntu 20.04"
                      key-name: osism-zuul
                      console-log: true
      become: true
