---
# defaults file for zuul-ci

###############################################################################
# Generic
###############################################################################

operator_user: ubuntu
operator_group: "{{ operator_user }}"
zuul_host: "{{ inventory_hostname }}"
zookeeper_fqdn: "zookeeper_1.example.org"
base_conf_dir: /opt/zuul-ci
component_conf_dirs:
  nodepool_builder: "{{ base_conf_dir }}/nodepool_builder_configuration"
  nodepool_launcher: "{{ base_conf_dir }}/nodepool_launcher_configuration"
  zookeeper: "{{ base_conf_dir }}/zookeeper_configuration"
  zuul: "{{ base_conf_dir }}/zuul_configuration"
  certs: "{{ base_conf_dir }}/certs"
  ssh_keys: "{{ base_conf_dir }}/ssh_keys"
  web: "{{ base_conf_dir }}/web"
  log_server: "{{ base_conf_dir }}/log_server"
  scheduler: "{{ base_conf_dir }}/scheduler"


###############################################################################
# Zuul
###############################################################################

connections:
  githubzuulapp:
    driver: github
    webhook_token: "webhooksecretvalue"
    app_id: "123456"
    app_key: "/etc/zuul/pem-files/githubzuulapp.pem"
  opendevorg:
    name: opendev
    driver: git
    baseurl: https://opendev.org

tenants:
  - tenant:
      name: my-tenant-name  # only use names that can be processed by urls.
      source:
        opendevorg:
          untrusted-projects:
            - zuul/zuul-jobs:
                include:
                  - job
        githubzuulapp:
          config-projects:
            - tibeerorg/zuul_config:
                load-branch: main
          untrusted-projects:
            - tibeerorg/zuul_demo_repo


###############################################################################
# docker
###############################################################################

docker_registry: index.docker.io

port_list:
  web: 9000
  log_server: 8000

nodepool_tag: "5.0.0"
zookeeper_tag: "3.7.0"
zuul_tag: "5.0.0"

image_list:
  nodepool_builder: "{{ docker_registry }}/zuul/nodepool-builder:{{ nodepool_tag }}"
  nodepool_launcher: "{{ docker_registry }}/zuul/nodepool-launcher:{{ nodepool_tag }}"
  zuul_executor: "{{ docker_registry }}/zuul/zuul-executor:{{ zuul_tag }}"
  zuul_web: "{{ docker_registry }}/zuul/zuul-web:{{ zuul_tag }}"
  zuul_scheduler: "{{ docker_registry }}/zuul/zuul-scheduler:{{ zuul_tag }}"
  zookeeper: "{{ docker_registry }}/zookeeper:{{ zookeeper_tag }}"
  mariadb: "{{ docker_registry }}/mariadb:latest"
  log_server: "{{ docker_registry }}/httpd:alpine"

database:
  user_name: zuul
  user_pass: secret
  root_pass: rootpassword
  db_name: zuul

container_name:
  mariadb: "zuul_mariadb"
  zookeeper: "zuul_zookeeper"
  nodepool_builder: "zuul_nodepool_builder"
  nodepool_launcher: "zuul_nodepool_launcher"
  zuul_executor: "zuul_executor"
  zuul_scheduler: "zuul_scheduler"
  zuul_web: "zuul_web"
  log_server: "zuul_log_server"


###############################################################################
# Nodepool
###############################################################################

nodepool_labels:
  labels:  # we need this sub-key. limitation of to_nice_yaml library
    - name: ubuntu-focal

nodepool_providers:
  providers:  # we need this sub-key. limitation of to_nice_yaml library
    - name: static-vms
      driver: static
      pools:
        - name: main
          nodes:
            - name: zuul_worker_node_1
              labels: ubuntu-focal  # make sure nodepool_labels has this
              host-key-checking: false
              python-path: /usr/bin/python3
              username: root
