---
# tasks file for zuul-ci

# unfortunately zookeeper can only read certificates with group
# permissions. therefore the base directory can only be entered
# by the owner. the files in this directory will have read
# permissions for all others too.
- name: create base config directory
  file:
    state: directory
    path: "{{ base_conf_dir }}"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0755

- name: create component config directories
  file:
    state: directory
    path: "{{ item['value'] }}"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0755
  loop: "{{ component_conf_dirs | dict2items }}"

- name: create log directory
  file:
    state: directory
    path: /var/log/zuul
    owner: "{{ zuul_user }}"
    group: "{{ zuul_user }}"
    mode: 0755
  become: true

- name: create nodepool directories
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ zuul_user }}"
    group: "{{ zuul_user }}"
    mode: 0755
  become: true
  loop:
    - /srv/dib_cache
    - /srv/dib_tmp
    - /srv/nodepool
    - /srv/nodepool/builds
    - /srv/nodepool/elements

- name: include copy tasks
  include_tasks: copy_tasks.yml

- name: include template tasks
  include_tasks: template_tasks.yml

- name: include generation of certificates and keys
  include_tasks: generate_certs_and_keys.yml

- name: Rotate logs
  include_role:
    name: logrotate
  vars:
    logrotate_rotate: 30
  loop:
    - /var/log/zuul/zuul.log
    - /var/log/zuul/debug.log
    - /var/log/zuul/web.log
    - /var/log/zuul/web-debug.log
  loop_control:
    loop_var: logrotate_file_name

- name: start zuul
  community.docker.docker_compose:
    project_src: "{{ base_conf_dir }}"
    project_name: zuul
